linux_gmp:
  tags:
    - ci.inria.fr
    - small
  stage: build
  script:
    - autoreconf -i
    - CFLAGS="-Wuninitialized -fsanitize=undefined -fno-sanitize-recover=all -Wall -Wextra -Wdeclaration-after-statement -Wshadow -Wstrict-prototypes -Wmissing-prototypes" ./configure
    - make
    - make check
  artifacts:
    paths:
      - tests/test-suite.log
