linux_gmp:
   tags:
      - ci.inria.fr
      - small
   image: debian:stable
   script:
      - apt-get update
      - apt-get install -y autoconf git libtool libmpfr-dev make texinfo
      - autoreconf -vfi
      - CFLAGS="-Wuninitialized -fsanitize=undefined -fno-sanitize-recover=all -Wall -Wextra -Wdeclaration-after-statement -Wshadow -Wstrict-prototypes -Wmissing-prototypes" ./configure
      - make
      - make check
   artifacts:
      paths:
         - config.log
         - tests/test-suite.log
